### ISSUE TITLE
Need a way to choose playback speed from the js embed

### ISSUE THREAD

**Issue by tavomaciel** [gfycat/gfycat.js#5]
RIght now you can't set the playback speed (well, if there's a way, it's not documented)

For example, I wanted to embed an gfycat on my page and set its playback speed to 0.5 at start.

Something like: 

```javascript
<img class="gfyitem" data-speed="0.5" data-id="SmoothInfamousFirefly"/>
```

would be fine.

**Comment by koshka** [comment]
Hey @tavomaciel, thank you for this feature request. 
Added `data-playback-speed` option in the latest release.
Check [README.md](https://github.com/gfycat/gfycat.js/blob/master/README.md) file for more information.
