### ISSUE TITLE
Some don't load on page with multiple GFYCAT

### ISSUE THREAD

**Issue by kerosity** [gfycat/gfycat.js#6]
I have a page that has 17 GFYCAT embeds on it. The embed works fine with 1-2. After that I loaded all of them, and some of them don't work. They are all set to not autoplay.

There are multiple issues:

Some don't play at all (preview image only, no play button).

Some have play button but:
1) won't play all the way through
2) or will play all the way through but won't loop.

Others work fine.

I'm using the current version of the code.

**Comment by leogg** [comment]
Please try the version from the WP plugin repository:
https://wordpress.org/plugins/wp-gfycat/

**Comment by kerosity** [comment]
I used that plugin before trying to do it manually. I had the same problem.

**Comment by leogg** [comment]
Yep, the js version from http://test.gfycat.com/gfycat_test_june25.js won't
work. The attributes are different. We're using a slightly modified version
of https://github.com/gfycat/gfycat.js/

**Comment by kerosity** [comment]
I tried the one you just linked to. I downloaded it, copied both of the .js files into a single file. Linked to it. And I had the same issue as the Wordpress plugin.

Is there a way to privately share the page with you?

**Comment by leogg** [comment]
Sure! Send me an e-mail to leo.telsen AT gmail.com and I'll take a look at
it.

**Comment by kerosity** [comment]
Thank you! I sent it over.

**Comment by kerosity** [comment]
Update: I was playing with this on another site I own and it's broken there also (most updated version of the gfycat.js script).

I don't know if this helps, but it starts to break on the seventh embed. AThey load perfectly fine at 6, and they start to have problems as soon as you add the 7th.

**Comment by jajakobyly** [comment]
We have identical issue here: https://intellij-rust.github.io/features/

**Comment by koshka** [comment]
@kerosity Updated version of JS embed was just released.
Please, try to use it and contact us if you notice any issues.
README file has a list of all the changes and new features.
