### ISSUE TITLE
Gifs not showing at all in firefox

### ISSUE THREAD

**Issue by Shaderboy** [gfycat/gfycat.js#8]
Heyo, I tried adding the script via the given url (https://assets.gfycat.com/gfycat.js), but the network tab didn't show it loading it at all. Downloading the file and loading it from the local path works. But now, even though the script is loading, it doesn't load the gif.

Here's how I've attempted to place it in html:

`<img class='gfyitem' data-id='BestYellowishElephantseal'>`

Also tried:

`<div class="gfyitem" data-title=true data-autoplay=false data-controls=true data-expand=false data-id="BestYellowishElephantseal" ></div> `

But neither of these loads anything. In both cases, the div just shows up empty on the page. The console does print out "0" and then "BestYellowishElephantseal", but nothing on the page.

Should note that this only happens in firefox. Works fine in chromium and chrome. Not sure about IE and safari and opera.

**Comment by koshka** [comment]
Updated version of JS embed was just released.
Please, try to use it again.
Make sure that you call `gfyCollection.init()` when `gfyitem` elements are actually on a page.
